# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnowxRag < Formula
  desc "Per-project RAG memory MCP server for AI coding agents"
  homepage "https://github.com/enowdev/enowx-rag"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enowdev/enowx-rag/releases/download/v0.1.0/enowx-rag_0.1.0_darwin_amd64.tar.gz"
      sha256 "1d4d9741245585e02e25c59a456637871caff9cf3b7a1302e4668903eda3f35b"

      define_method(:install) do
        bin.install "enowx-rag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enowdev/enowx-rag/releases/download/v0.1.0/enowx-rag_0.1.0_darwin_arm64.tar.gz"
      sha256 "b026e1345e15461f98d3791d9ab51848784ee0ea1e1429b8095aa13a4120a06c"

      define_method(:install) do
        bin.install "enowx-rag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enowdev/enowx-rag/releases/download/v0.1.0/enowx-rag_0.1.0_linux_amd64.tar.gz"
      sha256 "f3aa7a4b52c61b3169ab320502dced36946a68d6e247097f42ea9080fe997613"
      define_method(:install) do
        bin.install "enowx-rag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enowdev/enowx-rag/releases/download/v0.1.0/enowx-rag_0.1.0_linux_arm64.tar.gz"
      sha256 "9176f5e2bb1f59e07959cf6758ce52aac40317a57a3cc22f3bb7c0da9f1e8d4c"
      define_method(:install) do
        bin.install "enowx-rag"
      end
    end
  end

  test do
    system "#{bin}/enowx-rag", "version"
  end
end
